AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*" 
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    - "Gemfile"
    - "test/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

  DisplayCopNames: true

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Layout/EndOfLine:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Max: 30